matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: SWIFT_VERSION=4.1
    - os: osx
      osx_image: xcode10
      env: SWIFT_VERSION=4.2
    - os: linux
      env: SWIFT_VERSION=4.1
    - os: linux
      env: SWIFT_VERSION=4.2
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget --output-document /tmp/SwiftLint.pkg https://github.com/realm/SwiftLint/releases/download/0.27.0/SwiftLint.pkg &&
    sudo installer -pkg /tmp/SwiftLint.pkg -target /; fi
script:
  - swift test
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then swiftlint; fi
